from .utils import get_by_id, SparseList


__all__ = ('manufacturers', 'get_by_mid')


# Keys: ("ID", "Manufacturer", "Location", "Date last modified"),
manufacturers_tuple = (
    (0, "Reserved", "", ""),
    (1, "Allied Signal Inc.", "Elyria, OH USA", ""),
    (2, "Allison Transmission, GMC", "Indianapolis, IN USA", ""),
    (3, "Ametek, US Gauge Division", "Sellersville, PA USA", ""),
    (4, "Ametek-Dixson", "Grand Junction, CO USA", ""),
    (5, "AMP Inc.", "Harrisburg, PA USA", ""),
    (6, "Berifors Electronics AB", "Stockholm, Sweden", ""),
    (7, "Case Corp.", "Burr Ridge, IL USA", ""),
    (8, "Caterpillar Inc.", "Peoria, IL USA", ""),
    (9, "Chrysler Corp.", "Auburn Hills, MI USA", ""),
    (10, "Cummins Inc (formerly Cummins Engine Co)", "Columbus, IN USA", ""),
    (11, "Dearborn Group Inc.", "Indianapolis, IN & Farmington Hills, MI USA", ""),
    (12, "Deere & Company, Precision Farming", "East Moline, IL USA", ""),
    (13, "Delco Electronics", "Kokomo, IN USA", ""),
    (14, "Detroit Diesel Corporation", "Detroit, MI USA", ""),
    (15, "Dickey-john Corp.", "Auburn, IL USA", ""),
    (16, "Eaton Corp", "Southfield, MI USA", ""),
    (17, "Eaton Corp, Corp Res & Dev", "Milwaukee, WI USA", ""),
    (18, "Eaton Corp, Transmission Div.", "Kalamazoo, MI USA", ""),
    (19, "Eaton Corp. Trucking Info Services", "Clemmons, NC USA", ""),
    (20, "Eaton Ltd", "Worsley, England", ""),
    (21, "Echlin Inc., Midland Brake Inc.", "Kansas City, MO USA", ""),
    (22, "Ford Motor Co. Electronic Concepts & Systems", "Dearborn, MI USA", ""),
    (23, "Ford Motor Co. Heavy Truck", "Dearborn, MI USA", ""),
    (24, "Ford Motor Co. Vehicle Controls", "Dearborn, MI USA", ""),
    (25, "Daimler Trucks North America LLC (formerly Freightliner LLC)", "Portland, OR USA", "21-May-08"),
    (26, "General Motors Corp, Service Technology Grp", "Romulus, MI USA", ""),
    (27, "GMC", "Troy, MI USA", ""),
    (28, "Grote Ind. Inc.", "Madison, IN USA", ""),
    (29, "Hino Motors Ltd.", "Tokyo, Japan", ""),
    (30, "Isuzu Motors Ltd", "Kawasaki, Japan", ""),
    (31, "J Pollak Corp", "Boston, MA USA", ""),
    (32, "Jacobs Vehicle Systems", "Bloomfield, CT USA", "1-Jul-98"),
    (33, "John Deere", "Waterloo, IA USA", ""),
    (34, "Kelsey Hayes Co.", "Livonia, MI USA", ""),
    (35, "Kenworth Truck Co.", "Kirkland, WA USA", ""),
    (36, "Lucas Ind.", "Solihull WMidlnd, England", ""),
    (37, "Mack Trucks Inc.", "Hagerstown, MD USA", ""),
    (38, "Micro Processor Systems Inc.", "Sterling Hts, MI USA", ""),
    (39, "Microfirm Inc.", "Stillwater, OK USA", ""),
    (40, "Motorola AIEG Inc.", "Northbrook, IL USA", ""),
    (41, "Motorola Inc.", "Schaumburg, IL USA", ""),
    (42, "International Truck and Engine Corporation - Engine Electronics  (formerly Navistar Intl Trans Co. Engine Electronics)", "Warrenville, IL  USA", "7-Jan-03"),
    (43, "International Truck and Engine Corporation - Vehicle Electronics (formerly Navistar Intl Trans Corp.)", "Warrenville, IL  USA", "7-Jan-03"),
    (44, "Nippondenso Co. Ltd.", "Kariya Aichi, Japan", ""),
    (45, "PACCAR", "Mount Vernon, WA USA", ""),
    (46, "Noregon Systems, Inc  (formerly Parasoft Computing Solutions)", "Winston Salem, NC USA", "30-Oct-10"),
    (47, "Phillips Semiconductor", "Sunnyvale, CA USA", ""),
    (48, "Pollak Alphabet", "El Paso, TX USA", ""),
    (49, "RE America Inc.", "Cleveland, OH USA", ""),
    (50, "Robert Bosch Corp", "Broadview, IL  USA", ""),
    (51, "Robert Bosch GmbH", "Stuttgart, Germany", ""),
    (52, "Meritor Automotive, Inc. (formerly Rockwell Automotive)", "Troy, MI USA", "1-Nov-97"),
    (53, "Continental Automotive Systems US, Inc. (formerly Rockwell Land Transportation)", "Cedar Rapids, IA USA", "9-Nov-08"),
    (54, "Meritor Wabco", "Troy, MI USA", ""),
    (55, "Ryder System Inc.", "Miami, FL USA", ""),
    (56, "SAIC", "San Diego, CA USA", ""),
    (57, "Sauer-Danfoss Co (formerly Sauer Sundstrand Co.)", "Minneapolis, MN USA", "10-Aug-00"),
    (58, "SPX Corporation, OTC Div", "Owatonna, MN USA", ""),
    (59, "VES Inc.", "Rock Hill, SC USA", ""),
    (60, "Volvo Trucks North America Inc.", "Greensboro, NC USA", "1-Feb-99"),
    (61, "Volvo Truck Corp.", "Gothenburg, Sweden", ""),
    (62, "Wabco", "Hanover, Germany", ""),
    (63, "ZF Industries Inc.", "Vernon Hills, IL USA", ""),
    (64, "unused (formerly SpectraPrecision Laserplane then SpectraPhysics)", "", "15-Feb-01"),
    (65, "MAN Nutzfahrzeuge AG", "Munich, Germany", "1-Feb-99"),
    (66, "John Deere Construction Equipment Division", "Dubuque, IA USA", "11-Nov-99"),
    (67, "John Deere Coffeyville Works (formerly Funk Manufacturing Company)", "Coffeyville, KS USA", "22-Dec-06"),
    (68, "Scania", "Sodertalje, Sweden", ""),
    (69, "Trimble Navigation", "", ""),
    (70, "Flex-coil Limited", "Saskatoon, SK Canada", ""),
    (71, "Vansco Electronics Ltd.", "Winnipeg, MAN Canada", ""),
    (72, "Sisu Corporation, ESPOO", "Finland", ""),
    (73, "LeTourneau, Inc.", "Longview, TX  USA", ""),
    (74, "Eaton Axle-Brake Division", "Kalamazoo, MI USA", ""),
    (75, "Deere & Co, Agricultural Division", "", "1-Feb-98"),
    (76, "unused (formerly Deere & Co, Construction Division)", "", "11-Nov-99"),
    (77, "Deere Power Systems Group", "", "1-Feb-98"),
    (78, "Frank W. Murphy Manufacturing, Inc", "Tulsa, OK USA", "1-Feb-98"),
    (79, "Daimler Benz AG - Engine Division (PBM)", "Stuttgart, Germany", "1-Feb-98"),
    (80, "Twin Disc, Inc.", "Racine, WI USA", "1-Apr-98"),
    (81, "Fire Research Corp.", "Nesconset, NY USA", "1-Apr-98"),
    (82, "Bobcat/Ingersoll-Rand (formerly Melroe/Ingersoll-Rand)", "Fargo, ND USA", "11-May-00"),
    (83, "Eaton VORAD Technologies", "San Diego, CA USA", "1-May-99"),
    (84, "New Holland UK Limited, Basildon", "Essex, UK", "11-Nov-99"),
    (85, "Kohler Co", "Kohler, WI USA", "11-Nov-99"),
    (86, "C. E. Niehoff & Company", "Evanston, IL USA", "11-Nov-99"),
    (87, "J.C. Bamford Excavators Ltd (JCB)", "Rocester, Staffordshire, UK", "11-Nov-99"),
    (88, "Satloc Precision GPS", "Scottsdale, AZ USA", "11-Nov-99"),
    (89, "Kverneland Group, Electronics Division", "Niew-Vennep, Netherlands", "10-Feb-00"),
    (90, "Knorr-Bremse SfN GmbH", "Munich, Germany", "11-May-00"),
    (91, "BSG Bodensee Steuergeraete GmbH", "Immenstaad, Germany", "11-May-00"),
    (92, "Ag-Chem Equipment Co., Inc.", "Minnetonka,  MN USA", "11-May-00"),
    (93, "Perkins Engines Company Ltd.", "Peterborough, UK", "10-Aug-00"),
    (94, "CNH Global N.V.", "Racine, WI USA", "10-Aug-00"),
    (95, "Pacific Insight Electronics Corp.", "Nelson, BC Canada", "10-Aug-00"),
    (96, "Mech@tronic IT GmbH", "Hetzenhausen, Germany", "9-Nov-00"),
    (97, "Ag Leader Technology, Inc.", "Ames, IA USA", "9-Nov-00"),
    (98, "Mueller-Elektronik GmbH & Co", "Salzkotten, Germany", "15-Feb-01"),
    (99, "International Transmissions Ltd (ITL)", "Wrexham, North Wales, UK", "25-Jan-01"),
    (100, "VDO Technik AG", "Ruthi, Switzerland", "21-Feb-01"),
    (101, "Sensoria", "San Diego, CA USA", "21-Feb-01"),
    (102, "AGCO GmbH & Co.", "Marktoberdorf, Germany", "13-Mar-01"),
    (103, "Agrocom GmbH & Co. Agrarsystem KG", "Bielefeld, Germany", "19-Apr-01"),
    (104, "Claas Selbstfahrende Erntemaschinen GmbH", "Harsewinkel, Germany", "19-Apr-01"),
    (105, "Kiepe Elektrik GmbH & Co. KG", "Duesseldorf, Germany", "25-May-01"),
    (106, "BAE Systems Controls, Inc.", "Johnson City, NY USA", "27-Jun-01"),
    (107, "Grimme Landmaschinen GmbH & Co. KG", "Damme, Germany", "28-Jun-01"),
    (108, "WTK-Elecktronik GmbH", "Neustadt, Germany", "30-Jul-01"),
    (109, "TeeJet Technologies Denmark (formerly LH Technologies ApS)", "Aabybro, Denmark", "5-Sep-08"),
    (110, "EPIQ Sensor-Nite", "Fenton, MI USA", "19-Sep-01"),
    (111, "Maschinenfabrik Bernhard Krone GmbH", "Spelle, Germany", "5-Oct-01"),
    (112, "MECALAC", "Annecy le Vieux, France", "31-Dec-01"),
    (113, "Stress-Tek, Inc.", "Kent, WA USA", "14-Jan-02"),
    (114, "EControls, Inc.", "San Antonio, TX USA", "21-Apr-02"),
    (115, "NACCO Materials Handling Group, Inc.", "Portland, OR USA", "1-May-02"),
    (116, "BEELINE Technologies", "Brisbane, QLD  Australia", "1-May-02"),
    (117, "HUSCO International", "Waukesha, WI USA", "29-May-02"),
    (118, "Intron GmbH", "Schwaebisch Hall, Germany", "28-Jul-02"),
    (119, "IntegriNautics", "Menlo Park, CA  USA", "30-Jul-02"),
    (120, "RDS Technology Ltd", "Minchinhampton, Stroud, UK", "24-Aug-02"),
    (121, "HED (Hydro Electronic Devices, Inc.)", "Hartford, WI  USA", "2-Sep-02"),
    (122, "FG Wilson (Engineering) Limited", "Larne, County Antrim, UK", "13-Sep-02"),
    (123, "Basler Electric", "Highland, IL  USA", "9-Nov-02"),
    (124, "Hydac Electronic", "Saarbruecken, Germany", "28-Jan-03"),
    (125, "Nevada Automotive Test Center", "Carson City, NV  USA", "20-Feb-03"),
    (126, "Driver Tech", "Salt Lake City, UT  USA", "20-Feb-03"),
    (127, "Holland USA", "Holland, MI  USA", "29-Mar-03"),
    (128, "Gerhard Duecker GmbH & Co. KG", "Stadtlohn, Germany", "29-Mar-03"),
    (129, "OMNEX Control Systems Inc.", "Port Coquitlam, BC, Canada", "31-Mar-03"),
    (130, "Nido - Universal Machines B.V.", "Holten, Netherlands", "28-Apr-03"),
    (131, "ITT Industries", "Eden Prarie, MN  USA", "5-Jun-03"),
    (132, "Mulag-Fahrzeugwerk", "Oppenau, Germany", "13-Jul-03"),
    (133, "Bucher Schoerling GmbH", "Hannover, Germany", "13-Jul-03"),
    (134, "Iris Technology Ltd", "Lancaster, Lancs, UK", "20-Jul-03"),
    (135, "Airmar Technology Corporation", "Milford, NH USA", "20-Aug-03"),
    (136, "Komatsu Ltd", "Hiratsuka, Kanagawa, Japan", "20-Aug-03"),
    (137, "Maretron", "Phoenix AZ, USA", ""),
    (138, "Georg Fritzmeier GmbH & Co. KG", "Grosshelfendorf, Germany", "15-Sep-03"),
    (139, "Caterpillar Trimble Control Technologies (CTCT), LLC", "Dayton, OH  USA", "15-Sep-03"),
    (140, "Lowrance Electronics, Inc.", "Tulsa, OK  USA", "18-Sep-03"),
    (141, "Thales Navigation Ltd.", "Surrey, UK", "1-Nov-03"),
    (142, "TRW Automotive (Commercial Steering Systems)", "Lafayette, IN USA", "20-Dec-03"),
    (143, "W. Gmeiner GmbH & Co.", "Kummersbruck,  Germany", "20-Dec-03"),
    (144, "Mercury Marine", "Fond du Lac, WI USA", "20-Dec-03"),
    (145, "MurCal Controls", "Palmdale, CA  USA", "31-Dec-03"),
    (146, "Maxima Technologies", "Lancaster, PA USA", "12-Jan-04"),
    (147, "Nautibus electronic GmbH", "Quern, Germany", "24-Jan-04"),
    (148, "Blue Water Data, Inc.", "Salem, NJ  USA", "24-Jan-04"),
    (149, "Holset", "Charleston, SC  USA", "24-Jan-04"),
    (150, "Fleetguard", "Nashville, TN  USA", "24-Jan-04"),
    (151, "Raven Industries Inc. - Flow Controls Division", "Sioux Falls, SD USA", "1-May-04"),
    (152, "elobau GmbH & Co. KG", "Leutkirch, Germany", "30-Nov-09"),
    (153, "Woodward, Industrial Controls Division", "Fort Collins, CO USA", "1-May-04"),
    (154, "Westerbeke Corporation", "Taunton, MA USA", "1-May-04"),
    (155, "Vetronix Corporation", "Santa Barbara, CA", "24-May-04"),
    (156, "ITT Industries - Cannon", "Shakopee, MN USA", "20-Jul-04"),
    (157, "ISSPRO Inc.", "Portland, OR USA", "20-Jul-04"),
    (158, "Firestone Industrial Products Company", "Carmel, IN USA", "5-Oct-04"),
    (159, "NTech Industries Inc", "Ukiah, CA USA", "5-Oct-04"),
    (160, "Nido", "Holten, Netherlands", "5-Oct-04"),
    (161, "Offshore Systems (UK) Ltd", "New Milton, Hampshire, UK", "5-Oct-04"),
    (162, "Axiomatic Technologies", "Mississauga, ON Canada", "5-Oct-04"),
    (163, "BRP Inc.", "Waukegan, IL USA", "5-Oct-04"),
    (164, "MTU Friedrichshafen GmbH (formerly DaimlerChrysler Off-Highway)", "Friedrichshafen, Germany", "14-Nov-06"),
    (165, "CPAC Systems AB", "Vastra Frolunda, Sweden", "5-Oct-04"),
    (166, "Phoenix International", "Fargo, ND USA", "5-Oct-04"),
    (167, "JLG Industries Inc", "McConnellsburg, PA  USA", "20-Oct-04"),
    (168, "Xantrex", "Burnaby, BC  Canada", "15-Dec-04"),
    (169, "Marlin Technologies Inc.", "Horicon, WI  USA", "15-Dec-04"),
    (170, "Computronics Corporation Ltd.", "Bentley, WA  Australia", "15-Dec-04"),
    (171, "Wachendorff Elektronik GmbH & Co. KG", "Geisenheim, Germany", "15-Dec-04"),
    (172, "Yanmar Marine USA", "Adairsville, GA USA", "15-Dec-04"),
    (173, "Ryeso, Inc.", "Palmdale, CA USA", "20-Jan-05"),
    (174, "AB Volvo Penta", "Goteburg, Sweden", "20-Jan-05"),
    (175, "Veris Technologies, Inc.", "Salina, KS USA", "20-Jan-05"),
    (176, "Moritz Aerospace", "Dublin, PA USA", "25-Jan-05"),
    (177, "Diagnostic Systems Associates", "Kalamazoo, MI USA", "2-Mar-05"),
    (178, "Siemens VDO Automotive AG", "Regensburg, Germany", "2-Mar-05"),
    (179, "TeeJet Technologies Springfield (formerly Midwest Technologies Illinois, LLC)", "Springfield, IL USA", "5-Sep-08"),
    (180, "Smart Power Systems", "Reed City, MI  USA", "15-Apr-05"),
    (181, "Coretronics, Inc.", "Eagle, ID USA", "15-Apr-05"),
    (182, "Vehicle Systems Engineering B.V.", "Veenendaal, Netherlands", "5-Jun-05"),
    (183, "KDS Controls, Inc", "Troy, MI USA", "5-Jun-05"),
    (184, "EIA Electronics", "Aartselaar, Belguim", "21-Jun-05"),
    (185, "Beede Electrical Instrument Company", "Penacock, NH  USA", "1-Jul-05"),
    (186, "Altronic, Inc", "Girard, OH  USA", "1-Aug-05"),
    (187, "Air-Weigh", "Eugene, OR USA", "12-Aug-05"),
    (188, "EMP Corp", "Escanaba, MI USA", "12-Aug-05"),
    (189, "QUALCOMM", "San Diego, CA USA", "12-Aug-05"),
    (190, "Hella KGaA Hueck & Co", "Lippstadt, Germany", "12-Aug-05"),
    (191, "XATA Corporation", "Eden Prairie, MN  USA", "3-Jan-11"),
    (192, "Floscan", "Seattle, WA  USA", "31-Aug-05"),
    (193, "Jeppesen Marine", "Portland, OR  USA", "31-Aug-05"),
    (194, "TriMark Corporation", "New Hampton, IA  USA", "31-Aug-05"),
    (195, "General Engine Products", "Livonia, MI  USA", "21-Oct-05"),
    (196, "LEMKEN GmbH & Co KG", "Alpen,  Germany", "21-Oct-05"),
    (197, "Mechron Power Systems", "Ottawa, ON Canada", "21-Oct-05"),
    (198, "Mystic Valley Communications", "Mystic, CT  USA", "21-Oct-05"),
    (199, "Actia Corp", "Elkhart, IN  USA", "21-Oct-05"),
    (200, "MGM Brakes", "Charlotte, NC  USA", "1-Nov-05"),
    (201, "Disenos y Tecnologia S.A.", "Barcelona, Spain", "10-Nov-05"),
    (202, "Curtis Instruments, Inc", "Mount Kisco, NY  USA", "14-Nov-05"),
    (203, "MILtronik GmbH", "Hilden, Germany", "3-Jan-06"),
    (204, "The Morey Corporation", "Woodridge, IL  USA", "13-Jan-06"),
    (205, "SmarTire Systems Inc", "Richmond, BC  Canada", "13-Jan-06"),
    (206, "port GmbH", "Halle, Germany", "2-Feb-06"),
    (207, "Otto Engineering", "Carpentersville, IL USA", "9-Feb-06"),
    (208, "Drew Technologies, Inc", "Whitmore Lake, MI  USA", "9-Feb-06"),
    (209, "Bell Equip. Co. SA (PTY) LTD", "Richards Bay, South Africa", "14-Mar-06"),
    (210, "Iteris, Inc.", "Anaheim, CA  USA", "14-Mar-06"),
    (211, "DNA Group", "Raleigh, NC USA", "22-Mar-06"),
    (212, "Sure Power Industries, Inc", "Tualatin, OR USA", "22-Mar-06"),
    (213, "CNH Belgium N.V.", "Zedelgem, Belgium", "24-Mar-06"),
    (214, "MC elettronica Srl", "Fiesso Umbertiano, Rovigo, Italy", "24-Mar-06"),
    (215, "Aetna Engineering/Fireboy-Xintex", "Grand Rapids, MI  USA", "3-Apr-06"),
    (216, "Paneltronics Inc.", "Hialeah Gardens, FL  USA", "2-Apr-06"),
    (217, "RM Michaelides Software & Elektronik GmbH", "Fulda, Germany", "21-Apr-06"),
    (218, "Gits Manufacturing Company", "Creston, IA  USA", "21-Apr-06"),
    (219, "Cat OEM Solutions", "Mossville, IL  USA", "25-Apr-06"),
    (220, "Beede Electrical Instrument Company, Inc", "Penacook, NH  USA", "29-Apr-06"),
    (221, "SiE", "Kempten/Allgaeu, Germany", "5-Jun-06"),
    (222, "Generac Power Systems, Inc.", "Waukesha, WI, USA", "3-Aug-06"),
    (223, "Vaueo Retarder Co., Ltd.", "Shajin, Baoan, Shen Zhen, China", "20-Aug-06"),
    (224, "EMMI Network, S.L.", "Gandia, Spain", "20-Aug-06"),
    (225, "SKF", "Gothenburg, Sweden", "31-Aug-06"),
    (226, "Monaco Coach Corporation", "Bend, OR  USA", "16-Sep-06"),
    (227, "Lykketronic A/S", "Loegstoer, Denmark", "15-Oct-06"),
    (228, "ZF Marine Electronics", "Mukilteo, WA  USA", "15-Oct-06"),
    (229, "Garmin International Inc.", "Olathe, KS  USA", "15-Oct-06"),
    (230, "Saucon Technologies", "Bethlehem, PA  USA", "6-Nov-06"),
    (231, "Topcon Positioning Systems, Inc.", "Livermore, CA  USA", "13-Nov-06"),
    (232, "TSD Integrated Controls", "Minneapolis, MN  USA", "13-Nov-06"),
    (233, "Yacht Monitoring Solutions Inc.", "Corpus Christi, TX USA", "14-Nov-06"),
    (234, "Mondial electronic GmbH", "Eggelsberg, Austria", "22-Dec-06"),
    (235, "SailorMade Marine Telemetry - Tetra Technology Ltd.", "Florianopolis, Brazil", "22-Dec-06"),
    (236, "Norac Systems International Inc", "Saskatoon, SK, Canada", "20-Jan-07"),
    (237, "Agtron Enterprises Inc", "Saskatoon, SK, Canada", "20-Jan-07"),
    (238, "ZF Friedrichshafen AG", "Friedrichshafen, Germany", "20-Jan-07"),
    (239, "May & Scofield Ltd", "Basingstoke, Hants, UK", "20-Jan-07"),
    (240, "Vanair Mfg", "New Buffalo, MI USA", "20-Jan-07"),
    (241, "Schneider Automation SAS", "Sophia Antipolis, France", "20-Jan-07"),
    (242, "Kokusandenki Co. Ltd", "Numazu, Shizuoka, Japan", "20-Jan-07"),
    (243, "eRide, Inc.", "San Francisco, CA USA", "18-Feb-07"),
    (244, "Techno-Matic", "Aars, Denmark", "11-Mar-07"),
    (245, "Capstan Ag Systems, Inc.", "Topeka, KS USA", "11-Mar-07"),
    (246, "Class 1, Inc", "Ocala, FL  USA", "24-Apr-07"),
    (247, "ePULSE", "Troy, MI  USA", "29-Apr-07"),
    (248, "Cooper Standard Automotive Active Systems Group", "Mitchell, ON  Canada", "15-Feb-08"),
    (249, "Schaltbau GmbH", "Munich, Germany", "15-Jun-07"),
    (250, "Kuhn Group", "Saverne, France", "15-Jun-07"),
    (251, "German Agricultural Society, Test Center (DLG)", "Gross-Ultstadt, Germany", "15-Jun-07"),
    (252, "Sensor-Technik Wiedemann GmbH", "Kaufbeuren, Germany", "15-Jun-07"),
    (253, "Mobile Control Systems", "Brussels, Belgium", "15-Jun-07"),
    (254, "GE Sensing", "St. Marys, PA  USA", "18-Jun-07"),
    (255, "MEAS France", "Toulouse, France", "20-Jul-07"),
    (256, "Tyco Electronics AMP", "Osan-Si, Kyunggi-Do, Korea", "20-Jul-07"),
    (257, "Honda Motor Co., Ltd", "Wako-city, Saitama, Japan", "28-Jul-07"),
    (258, "ARAG", "Rubiera, Italy", "13-Aug-07"),
    (259, "Jetter AG", "Ludwigsburg, Germany", "13-Aug-07"),
    (260, "Reichhardt GmbH Steuerungstechnik", "Hungen, Germany", "13-Aug-07"),
    (261, "Red Dot Corporation", "Seattle, WA  USA", "13-Aug-07"),
    (262, "HydraForce, Inc", "Lincolnshire, IL  USA", "13-Aug-07"),
    (263, "IMMI", "Westfield, IN  USA", "14-Aug-07"),
    (264, "Autolync", "Clayton, Victoria, Australia", "3-Sep-07"),
    (265, "MTS Sensor Technologie GmbH", "Luedenscheid, Germany", "5-Sep-07"),
    (266, "International Thermal Research Ltd", "Richmond, BC Canada", "27-Sep-07"),
    (267, "Red Lion Controls, Inc", "York, PA  USA", "27-Sep-07"),
    (268, "Accurate Technologies", "Wixom, MI USA", "13-Oct-07"),
    (269, "Saft America Inc.,  Space & Defense Division", "Cockeysville, MD  USA", "10-Nov-07"),
    (270, "Tennant", "Minneapolis, MN  USA", "10-Nov-07"),
    (271, "Cole Hersee", "South Boston, MA USA", "10-Nov-07"),
    (272, "Gross Mechanical Laboratories, Inc", "Hanover, MD USA", "30-Nov-07"),
    (273, "Active Research Limited", "Poole, Dorset, UK", "30-Nov-07"),
    (274, "LTW Technology Co., LTD", "Shinjuang City, Taipei Hsien, Taiwan, R.O.C.", "30-Nov-07"),
    (275, "Navico Egersund AS", "Egersund, Norway", "17-Dec-07"),
    (276, "Aqua-Hot Heating Systems", "Fort Lupton, CO  USA", "27-Jan-08"),
    (277, "LHP Telematics", "Columbus, IN  USA", "27-Jan-08"),
    (278, "Takata Electronics", "Farmington Hills, MI  USA", "15-Feb-08"),
    (279, "Geometris LP", "Houston, TX USA", "15-Feb-08"),
    (280, "Leica Geosystems Pty Ltd", "Brisbane, Queensland Australia", "18-Feb-08"),
    (281, "Precision Governors LLC", "Rockford, IL USA", "23-Feb-08"),
    (282, "Medallion Instrumentation Systems", "Spring Lake, MI  USA", "14-Mar-08"),
    (283, "CWF Hamilton & Co Ltd", "Christchurch, New Zealand", "14-Mar-08"),
    (284, "Mobile Tech Chile", "Concepcion, Bio Bio, Chile", "11-May-08"),
    (285, "Sea Recovery Corp", "Rancho Dominguez, CA USA", "11-May-08"),
    (286, "Coelmo srl", "Acerra, Italy", "11-May-08"),
    (287, "NTech Industries, Inc", "Ukiah, CA USA", "11-May-08"),
    (288, "Mitsubishi FUSO Truck & Bus Corp.", "Kawasaki, Kanagawa, Japan", "21-May-08"),
    (289, "Watlow", "St. Louis, MO USA", "21-May-08"),
    (290, "Kuebler GmbH", "VS-Schwenningen, Germany", "12-Jul-08"),
    (291, "Groeneveld Transport Efficiency BV", "Gorinchem, Netherlands", "12-Jul-08"),
    (292, "IKUSI - Angel Iglesias S.A.", "San Sebastian, Guipuzcoa, Spain", "12-Jul-08"),
    (293, "Spyder Controls Corp.", "Lacombe, AB Canada", "12-Jul-08"),
    (294, "Grayhill Inc.", "LaGrange, IL USA", "12-Jul-08"),
    (295, "BEP Marine", "Albany, North Shore City, New Zealand", "12-Jul-08"),
    (296, "micro dynamics GmbH", "Cologne, Germany", "16-Jul-08"),
    (297, "Zonar Systems Inc", "Seattle, WA USA", "26-Jul-08"),
    (298, "Holley Performance", "Bowling Green, KY USA", "26-Jul-08"),
    (299, "Rauch", "Sinzheim, Germany", "11-Aug-08"),
    (300, "Systron Donner Automotive", "Concord, CA USA", "11-Aug-08"),
    (301, "Parker Hannifin (UK) Ltd FDE group", "Thetford, Norfolk, UK", "14-Aug-08"),
    (302, "Nissin Kogyo Co., LTD", "Ueda-city, Nagano prefecture, Japan", "5-Sep-08"),
    (303, "CTS Corporation", "Elkhart, IN USA", "5-Sep-08"),
    (304, "EmpirBus AB", "Uddevalla, Sweden", "5-Sep-08"),
    (305, "NovAtel Inc", "Calgary, AB Canada", "20-Sep-08"),
    (306, "Sleipner Motor AB", "Fredrikstad, Norway", "20-Sep-08"),
    (307, "MAS Technologies", "Harleysville, PA  USA", "20-Sep-08"),
    (308, "Cyntrx", "De Pere, WI USA", "31-Oct-08"),
    (309, "Krauss-Maffei Wegmann GmbH & Co. KG", "Munich, Germany", "31-Oct-08"),
    (310, "TECNORD srl", "Modena, Italy", "31-Oct-08"),
    (311, "Patrick Power Products", "Elkridge, MD USA", "9-Nov-08"),
    (312, "Lectronix, Inc.", "Lansing, MI USA", "20-Nov-08"),
    (313, "Ilmor Engineering, Inc.", "Plymouth, MI USA", "2-Dec-08"),
    (314, "CSM GmbH", "Filderstadt, Germany", "8-Dec-08"),
    (315, "Icom Incorporated", "Osaka, Japan", "15-Dec-08"),
    (316, "ITT Flow Control", "Santa Ana, CA  USA", "18-Dec-08"),
    (317, "Navtronics Bvba", "Geel, Belgium", "19-Jan-09"),
    (318, "SAT Plan", "Beauvais Tille, Oise, France", "19-Jan-09"),
    (319, "Cadec Global", "Manchester, NH USA", "19-Jan-09"),
    (320, "Miedema Landbouwwerktuigenfabriek B.V.", "Winsum, Netherlands", "19-Jan-09"),
    (321, "Ultra Electronics", "Electrics, Cheltenham, UK", "19-Jan-09"),
    (322, "MICHENKA s.r.o.", "Koprivnice, Republic", "19-Jan-09"),
    (323, "Mobileye Vision Technologies Ltd.", "Jerusalem, Israel", "1-Feb-09"),
    (324, "Snap-on Diagnostics", "Lincolnshire, IL  USA", "1-Feb-09"),
    (325, "ASM Automation Sensorik Messtechnik GmbH", "Moosinning, Germany", "4-Feb-09"),
    (326, "Akron Brass Company", "Wooster, OH  USA", "12-Feb-09"),
    (327, "Sonceboz SA", "Sonceboz, Switzerland", "12-Feb-09"),
    (328, "Qwerty Electronik AB", "Bagarmossen, Sweden", "22-Mar-09"),
    (329, "Deif A/S", "Skive, Denmark", "22-Mar-09"),
    (330, "Kidde Aerospace and Defense", "Wilson, NC  USA", "22-Mar-09"),
    (331, "Horton, Inc.", "Roseville, MN  USA", "22-Mar-09"),
    (332, "HWH Corporation", "Moscow, IA  USA", "10-Apr-09"),
    (333, "Hadley Products Corporation", "Grandville, MI  USA", "19-Apr-09"),
    (334, "Takata-Petri AG", "Aschaffenburg, Germany", "19-Apr-09"),
    (335, "Evo Electric Ltd", "Woking, Surrey, UK", "15-May-09"),
    (336, "APE s.r.o.", "Bradlec, Czech Republic", "18-May-09"),
    (337, "Carraro S.p.A.", "Campodarsego, Italy", "18-May-09"),
    (338, "GRAF-SYTECO", "Tuningen, Germany", "21-Jun-09"),
    (339, "Competence Center ISOBUS e.V.", "Wallenhorst, Germany", "21-Jun-09"),
    (340, "Continental AG", "Hannover, Germany", "24-Jun-09"),
    (341, "Boning GmbH & Co", "Ganderkesee, Germany", "1-Jul-09"),
    (342, "THOMAS MAGNETE GmbH", "Herdorf, Germany", "25-Jul-09"),
    (343, "Baumer Group", "Villingen-Schwenningen, Germany", "25-Jul-09"),
    (344, "Parvus Corporation", "Salt Lake City, UT USA", "25-Jul-09"),
    (345, "Korean Maritime University", "Busan, Korea", "25-Jul-09"),
    (346, "Control Solutions", "Aurora, IL  USA", "9-Aug-09"),
    (347, "Honeywell", "Morristown, NJ USA", "21-Aug-09"),
    (348, "Amazonen Werke H. Dreyer", "Hasbergen, Germany", "21-Aug-09"),
    (349, "Suonentieto", "Kuopio, Finland", "21-Aug-09"),
    (350, "Noris Marine Systems GmbH & Co KG", "Nuremberg, Germany", "21-Aug-09"),
    (351, "Thrane & Thrane", "Gentofte, Denmark", "30-Aug-09"),
    (352, "SAME DEUTZ-FAHR", "Treviglio, Italy", "13-Sep-09"),
    (353, "Hegemon Electronics, Inc.", "Sterling Heights, MI  USA", "20-Sep-09"),
    (354, "Junkkari OY", "Yliharma, Finland", "8-Oct-09"),
    (355, "Mastervolt International B.V.", "Amsterdam, Netherlands", "9-Oct-09"),
    (356, "Fischer Panda Generators, Inc", "Oakland Park, FL USA", "20-Oct-09"),
    (357, "Hardi International A/S", "Taastrup, Denmark", "8-Nov-09"),
    (358, "Victron Energy BV", "Almere-Haven, Netherlands", "8-Nov-09"),
    (359, "Ludwig Bergmann GmbH", "Goldenstedt, Germany", "8-Nov-09"),
    (360, "HJS Emission Technology GmbH & Co KG (formerly HJS Fahrzeugtechnik GmbH & Co KG)", "Menden, Germany", "3-Feb-11"),
    (361, "InMach", "Ulm, Germany", "15-Jan-10"),
    (362, "Alois Poettinger Maschinenfabrik GmbH", "Grieskirchen, Austria", "15-Jan-10"),
    (363, "BEI Duncan", "Goleta, CA USA", "30-Jan-10"),
    (364, "OEM Controls Inc.", "Shelton, CT USA", "30-Jan-10"),
    (365, "Digi-Star, LLC", "Fort Atkinson, WI USA", "30-Jan-10"),
    (366, "Viewnyx Corp.", "Kanata, ON Canada", "30-Jan-10"),
    (367, "Fliegl Agrartechnik", "Toeging, Germany", "30-Jan-10"),
    (368, "HANSENHOF_electronic", "Reifland, Germany", "30-Jan-10"),
    (369, "Power Torque Engineering Ltd", "Coventry, UK", "14-Feb-10"),
    (370, "Rolls-Royce Marine AS", "Aalesund, Norway", "15-May-10"),
    (371, "Heinzmann GmbH & Co. KG", "Schoenau, Germany", "1-Apr-10"),
    (372, "Delphi", "Auburn Hills, MI  USA", "1-Apr-10"),
    (373, "Electronic Design Inc.", "Sheboygan, WI  USA", "15-May-10"),
    (374, "Northern Lights, Inc.", "Seattle, WA  USA", "15-May-10"),
    (375, "Williams Controls Inc.", "Portland, OR  USA", "15-May-10"),
    (376, "Quake Global", "San Diego, CA  USA", "15-Jun-10"),
    (377, "ifm electronic gmbh", "Essen, Germany", "15-Jun-10"),
    (378, "Glendinning Marine Products", "Conway, SC  USA", "15-Jun-10"),
    (379, "Yamabiko Corporation", "Iwate, Japan", "20-Jun-10"),
    (380, "Suntech International Ltd.", "Seoul, Korea", "20-Jun-10"),
    (381, "B & G", "Romsey, UK", "20-Aug-10"),
    (382, "National Agricultural Research Organization", "Niigata, Japan", "20-Aug-10"),
    (383, "MCL Industries", "Pulaski, WI USA", "20-Aug-10"),
    (384, "Camano Light", "Camano Island, WA  USA", "20-Aug-10"),
    (385, "Johnson Outdoor Marine Electronics", "Alpharetta, GA  USA", "20-Aug-10"),
    (386, "JLG Automation BVBA", "Gent, Belgium", "20-Aug-10"),
    (387, "Orscheln Products, LLC", "Moberly, MO  USA", "20-Aug-10"),
    (388, "Innomatix, LLC", "Iowa City, IA  USA", "20-Aug-10"),
    (389, "Benchmark Electronics, Minnesota Division", "Rochester, MN  USA", "20-Aug-10"),
    (390, "Partech Inc.", "Lake Orion, MI  USA", "20-Aug-10"),
    (391, "Electronic Design for Industry, Inc", "Belpre, OH  USA", "20-Aug-10"),
    (392, "Tianyuan Technology Co Ltd.", "Shijiazhuang, China", "28-Aug-10"),
    (393, "Harvest Tec, Inc", "Hudson, WI  USA", "28-Aug-10"),
    (394, "Capi 2 Nederland BV", "Nuenen, Netherlands", "15-Sep-10"),
    (395, "GENTEC S.R.L.", "Villa Constitucion, Argentina", "20-Sep-10"),
    (396, "Beyond Measure", "Appleton, WI  USA", "3-Jan-11"),
    (397, "Sanyo-kiki Co Ltd.", "Okayama, Japan", "30-Oct-10"),
    (398, "Hilite International", "Marktheidenfeld, Germany", "30-Oct-10"),
    (399, "ISEKI & Co. Ltd.", "Ehime, Japan", "1-Nov-10"),
    (400, "Livorsi Marine", "Grayslake, IL  USA", "3-Nov-10"),
    (401, "Torqeedo GmbH", "Stamberg, Germany", "3-Nov-10"),
    (402, "Simma Software, Inc.", "Terre Haute, IN USA", "15-Dec-10"),
    (403, "Trackwell ADS, Inc.", "Houston, TX  USA", "15-Dec-10"),
    (404, "Com Nav Marine Ltd", "Richmond, BC  Canada", "15-Dec-10"),
    (405, "Wema System AS", "Bergen, Norway", "15-Dec-10"),
    (406, "Vecima Networks Inc.", "Saskatoon, SK  Canada", "15-Dec-10"),
    (407, "Comtech Mobile Datacom", "Germantown, MD  USA", "15-Dec-10"),
    (408, "Corvus Energy Ltd.", "Richmond, BC Canada", "15-Dec-10"),
    (409, "Transfluid S.r.L.", "Gallarate, Italy", "15-Dec-10"),
    (410, "COBO S.p.A. Divisione 3B6", "Castelletto sopra Ticino, Italy", "15-Dec-10"),
    (411, "Hy-Drive Technologies Ltd.", "Mississauga, ON  Canada", "23-Dec-10"),
    (412, "WebTech Wireless Inc.", "Burnaby, BC  Canada", "23-Dec-10"),
    (413, "Datapross Nijbroek bv", "Nijbroek, Netherlands", "4-Jan-11"),
    (414, "Cattron Group International", "Sharpsvillle, PA USA", "6-Jan-11"),
    (415, "Valid Manufacturing Ltd.", "Salmon Arm, BC  Canada", "7-Jan-11"),
    (416, "Kubota Corporation", "Sakai, Japan", "14-Jan-11"),
    (417, "KZValve", "Greenwood, NE  USA", "26-Jan-11"),
    (418, "Intellistick Inc", "Santa Ana, CA  USA", "26-Jan-11"),
    (419, "Fusion Electronics Ltd", "Auckland, New Zealand", "29-Jan-11"),
    (420, "Vermeer Corporation, ACS Group", "Pella, IA  USA", "31-Jan-11"),
    (421, "Vertex Standard Co, Ltd", "Tokyo, Japan", "11-Feb-11"),
    (422, "True Heading AB", "Danderyd, Sweden", "11-Feb-11"),
    (423, "BSM Wireless, Inc.", "Toronto, ON  Canada", "5-Mar-11"),
    (424, "Odyne LLC", "Waukesha, WI  USA", "5-Mar-11"),
    (425, "Methode Electronics Inc, MDI", "Chicago, IL  USA", "5-Mar-11"),
    (429, "Rota Engineering Ltd.", "Bury, Manchester, UK", "27-Apr-11"),
    (430, "Auteq Telematica S.A.", "Sao Paulo, Brazil", "27-Apr-11"),
    (431, "Tohatsu Corporation", "Tokyo, Japan", "27-Apr-11"),
    (432, "S&A Systems, Inc.", "Rockwall, TX  USA", "27-Apr-11"),
    (433, "Rowe Electronics", "Norwalk, IA  USA", "29-Apr-11"),
    (434, "Stored Energy Systems", "Longmont, CO  USA", "29-Apr-11"),
    (435, "Zunhammer GmbH", "Traunreut, Germany", "6-May-11"),
    (436, "Kinze Manufacturing", "Williamsburg, IA", "18-May-11"),
    (437, "Digital Yacht Limited", "Bristol, UK", "18-May-11"),
    (438, "Comar Systems Ltd", "Cowes, Isle of Wight, UK", "18-May-11"),
    (1850, "Teleflex", "Limerick, PA  USA", "20-Jul-03"),
    (1851, "RayMarine", "Portsmouth, Hampshire, UK", "20-Jul-03"),
    (1852, "Navionics", "Wareham, MA  USA", "20-Jul-03"),
    (1853, "Japan Radio Co", "Seattle, WA  USA", "20-Jul-03"),
    (1854, "Northstar Technologies", "Acton, MA  USA", "20-Jul-03"),
    (1855, "Furuno USA", "Camas, WA  USA", "20-Jul-03"),
    (1856, "Trimble", "Sunnyvale, CA  USA", "20-Jul-03"),
    (1857, "Simrad", "Egersund, Norway", "20-Jul-03"),
    (1858, "Litton", "Charlottesville, VA  USA", "20-Jul-03"),
    (1859, "Kvasar AB", "Kinnahult, Sweden", "20-Jul-03"),
    (1860, "MMP", "Fircrest, WA  USA", "20-Jul-03"),
    (1861, "Vector Cantech", "Novi, MI  USA", "20-Jul-03"),
    (1862, "Sanshin", "Shizuoka, Japan", "20-Jul-03"),
    (1863, "Thomas G. Faria Co.", "Uncasville, CT  USA", "20-Jul-03"),
)


keys = ("id", "name", "location", "modified")


manufacturers = SparseList()
[manufacturers.insert(detail[0], detail) for detail in manufacturers_tuple]


get_by_mid = lambda mid: get_by_id(mid, keys, manufacturers)
