from .utils import get_by_id, SparseList


__all__ = ('addresses', 'get_by_sa')


# Keys: ("Source Address ID", "Name", "Notes", "Date last modified"),
addresses_tuple = (
    (0, "Engine #1", "The #1 on the Engine CA is to identify that this is the first PA being used for the particular function, Engine. It may only be used for the NAME Function of 0, Function Instance 0, and an ecu instance of 0, which is commonly know as the 'first engine.", ""),
    (1, "Engine #2", "The #2 on the Engine CA is to identify that this is the second PA available for use for the  function, Engine. It may be used by the 'second' engine (Function 0, Function Instance 1, ECU Instance 0), but it may also be used by the second ecu on the first", ""),
    (2, "Turbocharger", "Turbocharger used on the engine.  May only be used for the NAME Function of 133, Industry Group 0, Vehicle System 0.", "19-Feb-04"),
    (3, "Transmission #1", "The first transmission - may only be used for the NAME Function of 3, Function Instance 0, and an ecu instance of 0.", ""),
    (4, "Transmission #2", "The second PA available for use for the function, Transmission. It may be used by the 'second' transmission (Function 3, Function Instance 1, ECU Instance 0), but it may also be used by the second ecu on the first transmission (Function 3, Function Instan"),
    (5, "Shift Console - Primary", "The shift console mounted in the normal drivers position", ""),
    (6, "Shift Console - Secondary", "A shift console mounted remotely from the normal drivers position (May not be used for any ecu instances of the primary shift console)", ""),
    (7, "Power TakeOff - (Main or Rear)", "", ""),
    (8, "Axle - Steering", "", ""),
    (9, "Axle - Drive #1", "The first drive axle - may only be used for the NAME Function of 8, Function Instance 0, and an ecu instance of 0.", ""),
    (10, "Axle - Drive #2", "The second PA available for use for the function, Axle, Drive. It may be used by the 'second' drive axle (Function 8, Function Instance 1, ECU Instance 0), but it may also be used by the second ecu on the first drive axle (Function 8, Function Instance 0"),
    (11, "Brakes - System Controller", "", ""),
    (12, "Brakes - Steer Axle", "", ""),
    (13, "Brakes - Drive axle #1", "The brakes on the first drive axle - may only be used for the NAME Function of 11, Function Instance 0, and an ecu instance of 0.", ""),
    (14, "Brakes - Drive Axle #2", "The second PA available for use for the function, Brakes on a Drive Axle. It may be used by the 'second' drive axle brakes (Function 11, Function Instance 1, ECU Instance 0), but it may also be used by the second ecu on the first drive axle brakes (Functi"),
    (15, "Retarder - Engine", "Engine Compression Braking", ""),
    (16, "Retarder - Driveline", "", "", ""),
    (17, "Cruise Control", "Speed-based control"),
    (18, "Fuel System", "", ""),
    (19, "Steering Controller", "", ""),
    (20, "Suspension - Steer Axle", "", ""),
    (21, "Suspension - Drive Axle #1", "The suspension on the first drive axle - may only be used for the NAME Function of 18, Function Instance 0, and an ecu instance of 0.", ""),
    (22, "Suspension - Drive Axle #2", "The second PA available for use for the  function, suspension on drive axle. It may be used by the 'second' drive axle's suspension system (Function 18, Function Instance 1, ECU Instance 0), but when there is no second drive axle it may be used by the sec"),
    (23, "Instrument Cluster #1", "The first instrument cluster - may only be used for the NAME Function of 19, Function Instance 0, and an ecu instance of 0. 17-Jun-01"),
    (24, "Trip Recorder", "", ""),
    (25, "Passenger-Operator Climate Control #1", "The first climate control - may only be used for the NAME Function of 21, Function Instance 0, and an ecu instance of 0, and must be associated with the driver (operator) climate control, when there are multiple climate control systems.", ""),
    (26, "Alternator/Electrical Charging System", "Vehicle's primary charging controller", "10-Feb-00"),
    (27, "Aerodynamic Control", "", ""),
    (28, "Vehicle Navigation", "", ""),
    (29, "Vehicle Security", "", "", ""),
    (30, "Electrical System", "This may include Load Centers, Fuseboxes, & Power Distribution boards", "19-Nov-03"),
    (31, "Starter System", "", ""),
    (32, "Tractor-Trailer Bridge #1", "The first Tractor mounted bridge leading to trailer(s) - may only be used for the NAME Function of , Function Instance 0, and an ecu instance of 0. 10-Feb-99"),
    (33, "Body Controller", "", ""),
    (34, "Auxiliary Valve Control or Engine Air System Valve Control", "This should be used for auxiliary valve control or engine air system valve control.  May be used with NAME Function 142, 143, 147, or 148 in Industry group 0, Vehicle system group 0.  19-Nov-09", "Approved"),
    (35, "Hitch Control", "Straight truck hitch (NOT Ag hitch n it is in IG 2)"),
    (36, "Power TakeOff (Front or Secondary)", "", ""),
    (37, "Off Vehicle Gateway", "", ""),
    (38, "Virtual Terminal (in cab)", "", ""),
    (39, "Management Computer #1", "The first Management Computer - may only be used for the NAME Function of 30, Function Instance 0, and an ecu instance of 0.", "10-Feb-99"),
    (40, "Cab Display #1", "The first Cab Display - may only be used for the NAME Function of 60, Function Instance 0, and an ecu instance of 0.", "17-Jun-01"),
    (41, "Retarder, Exhaust, Engine #1", "The first engine exhaust retarder - may only be used for the NAME Function of 12, Function Instance 0, and an ecu instance of 0.", ""),
    (42, "Headway Controller", "Forward-looking collision warning, collision avoidance, speed controller, or speed matching"),
    (43, "On-Board Diagnostic Unit", "", "", ""),
    (44, "Retarder, Exhaust, Engine #2", "The second PA available for use for the function, engine exhaust retarder.  It may be used by the 'second' engine's exhaust retarder (Function 12, Function Instance 1, ECU Instance 0), but in cases without a second engine it may also be used by the second"),
    (45, "Endurance Braking System", "", "", ""),
    (46, "Hydraulic Pump Controller", "", ""),
    (47, "Suspension - System Controller #1", "The first Suspension - System Controller - may only be used for the NAME Function of 35, Function Instance 0, and an ecu instance of 0."),
    (48, "Pneumatic - System Controller", "", ""),
    (49, "Cab Controller - Primary", "", "", ""),
    (50, "Cab Controller - Secondary", "", ""),
    (51, "Tire Pressure Controller", "", "", ""),
    (52, "Ignition Control Module #1", "The first Ignition Control Module - may only be used for the NAME Function of 39, Function Instance 0, and an ecu instance of 0.", ""),
    (53, "Ignition Control Module #2", "The second PA available for use for the function, Ignition Control Module.  It may be used by the 'second' engine's Ignition Control Module (Function 39, Function Instance 1, ECU Instance 0), but in cases without a second engine it may also be used by the"),
    (54, "Seat Control #1 The first seat control module - may only be used for the NAME Function of 40, Function Instance 0, and an ecu instance of 0, and must be associated with the driver seat, when there are multiple seats with separate controls. 10-Aug-00"),
    (55, "Lighting - Operator Controls", "", "", ""),
    (56, "Rear Axle Steering Controller #1", "", "", ""),
    (57, "Water Pump Controller", "", ""),
    (58, "Passenger-Operator Climate Control #2", "The second PA available for climate control - must be associated with the passenger climate control (NAME Function of 21, function instance 1, and an ecu instance of 0), when there are multiple climate control systems.  If only one climate control system", ""),
    (59, "Transmission Display - Primary", "Display to operate specifically in conjunction with the transmission control mounted in the normal drivers position"),
    (60, "Transmission Display - Secondary", "Secondary display to operate specifically in conjunction with the transmission control mounted remotely from the normal drivers position (May not be used for any ecu instances of the primary transmission display)", ""),
    (61, "Exhaust Emission Controller", " 10-Feb-99"),
    (62, "Vehicle Dynamic Stability Controller", "", " 10-Feb-99"),
    (63, "Oil Sensor", "", "20-May-99"),
    (64, "Suspension - System Controller #2", "", "20-May-99"),
    (65, "Information System Controller #1", "The first Information System Controller - may only be used for the NAME Function of 47, Function Instance 0, and an ecu instance of 0.  20-May-99"),
    (66, "Ramp Control", "Control of ramps, lifts, or tailgates", "20-May-99"),
    (67, "Clutch/Converter Unit", "Control of either the clutch and/or converter", "20-May-99"),
    (68, "Auxiliary Heater #1", "The first Auxiliary Heater - may only be used for the NAME Function of 50, Function Instance 0, and an ecu instance of 0.", "20-May-99"),
    (69, "Auxiliary Heater #2", "The second PA available for auxiliary heater - must be associated with the second auxiliary heater control (NAME Function of 50, Function Instance 1, and an ecu instance of 0), when there are multiple auxiliary heaters.  If only one auxiliary heater contr 20-May-99"),
    (70, "Engine Valve Controller", "Electronic control used to control actuation of engine intake and/or exhaust valves 17-Jun-01"),
    (71, "Chassis Controller #1", "The first Chassis Controller - may only be used for the NAME Function of 52, Function Instance 0, and an ecu instance of 0. 11-Nov-99"),
    (72, "Chassis Controller #2", "The second PA available for chassis control - must be associated with the second chassis (NAME Function of 52, Function Instance 1, and an ecu instance of 0), when there are multiple chassis.  If only one chassis on the vehicle then may be used for the se 11-Nov-99"),
    (73, "Propulsion Battery Charger  A device used to charge propulsion batteries in an electric vehicle from an off-board source of electrical energy.  10-Feb-00"),
    (74, "Communications Unit, Cellular", "Cellular communications device", "10-Feb-00"),
    (75, "Communications Unit, Satellite", "Satellite communications device", "10-Feb-00"),
    (76, "Communications Unit, Radio", "Radio communications device, either receiver only, transmitter only or transceiver", "10-Feb-00"),
    (77, "Steering Column Unit", "Device that gathers the operator inputs from switches/levers/etc located in and/or around the steering wheel/column", "10-Feb-00"),
    (78, "Fan Drive Controller", "Controls the main cooling fan operation", "11-May-00"),
    (79, "Seat Control #2 The second PA available for seat controls - must be associated with the passenger seat (NAME Function of 40, Function Instance 1, and an ecu instance of 0), when there are multiple seats with separate controls.  If only one seat then may be used for the s", "10-Aug-00"),
    (80, "Parking brake controller", "Module controlling the parking brake", "21-Aug-03"),
    (81, "Aftertreatment #1", "system gas intake Used for exhaust gas measurement such NOx or oxygen, etc.", "18-Feb-04"),
    (82, "Aftertreatment #1", "system gas outlet Used for exhaust gas measurement such NOx or oxygen, etc.", "18-Feb-04"),
    (83, "Safety Restraint System", "The safety restraint system can be for controlling activation of airbags, belt tensioners, roll over protection systems, etc.", "18-Feb-04"),
    (84, "Cab Display #2", "The second Cab Display, this can used for supplemental displays such as retarder display, driver information display, etc.", "10-Feb-05"),
    (85, "Diesel Particulate Filter Controller", "Used for Diesel Particulate Filter operation and monitoring such as pressure drop, intake temperature, outlet temperature, soot loading, HC injection, etc.", "16-Aug-07"),
    (86, "Aftertreatment #2", "system gas intake Used for exhaust gas measurement such as NOx or oxygen, etc. for exhaust bank #2.", "15-Nov-07"),
    (87, "Aftertreatment #2", "system gas outlet Used for exhaust gas measurement such NOx or oxygen, etc. for exhaust bank #2.", "15-Nov-07"),
    (88, "Safety Restraint System #2", "The second safety restraint system that can be for controlling activation of airbags, belt tensioners, roll over protection systems, etc.", "15-Nov-07"),
    (89, "Atmospheric Sensor", "Used for sensors which measure conditions such as air temperature, pressure and/or humidity", "15-Nov-07"),
    (90, "thru 127 are reserved for future assignment by SAE", "", "30-Dec-01"),
    (160, "Advanced emergency braking system", "", ""),
    (161, "Fifth Wheel Smart Systems", "", ""),
    (162, "Slope Sensor", "", ""),
    (163, "Catalyst Fluid Sensor", "", ""),
    (164, "On Board Diagnostic Unit #2", "", ""),
    (165, "Rear Steering Axle Controller #2", "", ""),
    (166, "Rear Steering Axle Controller #3", "", ""),
    (167, "Instrument Cluster #2", "", ""),
    (168, "Trailer #5 Bridge", "", ""),
    (169, "Trailer #5 Lighting-electrical", "", ""),
    (170, "Trailer #5 Brakes (ABS-EBS)", "", ""),
    (171, "Trailer #5 Reefer", "", ""),
    (172, "Trailer #5 Cargo", "", ""),
    (173, "Trailer #5 Chassis-Suspension", "", ""),
    (174, "Other Trailer #5 Devices", "", ""),
    (175, "Other Trailer #5 Devices", "", ""),
    (176, "Trailer #4 Bridge", "", ""),
    (177, "Trailer #4 Lighting-electrical", "", ""),
    (178, "Trailer #4 Brakes (ABS-EBS)", "", ""),
    (179, "Trailer #4 Reefer", "", ""),
    (180, "Trailer #4 Cargo", "", ""),
    (181, "Trailer #4 Chassis-Suspension", "", ""),
    (182, "Other Trailer #4 Devices", "", ""),
    (183, "Other Trailer #4 Devices", "", ""),
    (184, "Trailer #3 Bridge", "", ""),
    (185, "Trailer #3 Lighting-electrical", "", ""),
    (186, "Trailer #3 Brakes (ABS-EBS)", "", ""),
    (187, "Trailer #3 Reefer", "", ""),
    (188, "Trailer #3 Cargo", "", ""),
    (189, "Trailer #3 Chassis-Suspension", "", ""),
    (190, "Other Trailer #3 Devices", "", ""),
    (191, "Other Trailer #3 Devices", "", ""),
    (192, "Trailer #2 Bridge", "", ""),
    (193, "Trailer #2 Lighting-electrical", "", ""),
    (194, "Trailer #2 Brakes (ABS-EBS)", "", ""),
    (195, "Trailer #2 Reefer", "", ""),
    (196, "Trailer #2 Cargo", "", ""),
    (197, "Trailer #2 Chassis-Suspension", "", ""),
    (198, "Other Trailer #2 Devices", "", ""),
    (199, "Other Trailer #2 Devices", "", ""),
    (200, "Trailer #1 Bridge", "", ""),
    (201, "Trailer #1 Lighting-electrical", "", ""),
    (202, "Trailer #1 Brakes (ABS-EBS)", "", ""),
    (203, "Trailer #1 Reefer", "", ""),
    (204, "Trailer #1 Cargo", "", ""),
    (205, "Trailer #1 Chassis-Suspension", "", ""),
    (206, "Other Trailer #1 Devices", "", ""),
    (207, "Other Trailer #1 Devices", "", ""),
    (228, "Steering Input Unit", "", ""),
    (229, "Body Controller #2", "", ""),
    (230, "Body-to-Vehicle Interface Control", "", ""),
    (231, "Articulation Turntable Control", "", ""),
    (232, "Forward Road Image Processor", "", ""),
    (233, "Door Controller #3", "", ""),
    (234, "Door Controller #4", "", ""),
    (235, "Tractor/Trailer Bridge #2", "", ""),
    (236, "Door Controller #1", "", ""),
    (237, "Door Controller #2", "", ""),
    (238, "Tachograph", "", ""),
    (239, "Electric Propulsion Control Unit #1", "", ""),
    (240, "Electric Propulsion Control Unit #2", "", ""),
    (241, "Electric Propulsion Control Unit #3", "", ""),
    (242, "Electric Propulsion Control Unit #4", "", ""),
    (243, "Battery Pack Monitor #1", "", ""),
    (244, "Battery Pack Monitor #2 / APU #4", "", ""),
    (245, "Battery Pack Monitor #3 / APU #3", "", ""),
    (246, "Battery Pack Monitor #4 / APU #2", "", ""),
    (247, "Auxiliary Power Unit (APU) #1" "", ""),
    (248, "File Server / Printer", "On-board file and/or print server", "17-Jun-01"),
    (249, "Off Board Diagnostic-Service Tool #1", "The address for the first off board diagnostic service tool - may only be used for the NAME Function of 129, Industry Group 0, Function Instance 0, and an ECU instance of 0.", ""),
    (250, "Off Board Diagnostic-Service Tool #2", "The second preferred address available for use for the function 'Off Board Diagnostic-Service Tool'. It should only be used by the 'second' Off Board Diagnostic-Service Tool (Function 129, Industry Group 0, Function Instance 1, ECU Instance 0).", ""),
    (251, "On-Board Data Logger", "", "", ""),
    (252, "Reserved for Experimental Use", "", ""),
    (253, "Reserved for OEM", "", "", ""),
    (254, "Null Address", "", "", ""),
    (255, "GLOBAL (All-Any Node)", "", ""),
)


addresses = SparseList()
[addresses.insert(detail[0], detail) for detail in addresses_tuple]


keys = ("id", "name", "notes", "modified")


get_by_sa = lambda address: get_by_id(address, keys, addresses)
